AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    DynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
          AttributeDefinitions:
            - AttributeName: "id"
              AttributeType: "S"
          BillingMode: "PAY_PER_REQUEST"
          TableName: "todo-table"
          KeySchema:
            - AttributeName: "id"
              KeyType: "HASH"